############################################################
#  Configurazione Quarkus App                              #
############################################################
quarkus:
  application:
    name: orders-managment
    version: 1.0.0
  http:
    port: 8081
    auth:
      basic: false
    cors:
      ~: true
      origins: '*'
    root-path: /api/v1/app
  log:
    level: INFO
    #category:
    #  "io.quarkus":
    #    level: DEBUG
    file:
      enable: true
      path: "/tmp/application.log"
      level: TRACE
      format: "%d ${LOG_LEVEL_PATTERN:-%5p} [%c{2.}] | %m%n"
    console:
      enable: true
      format: "%d ${LOG_LEVEL_PATTERN:-%5p} [%c{2.}] | %m%n"
      level: DEBUG

  package:
    type: fast-jar
  profile: svil
  test:
    # The profile to use when testing the native image
    native-image-profile: svil

    # The profile to use when testing using @QuarkusTest
    profile: test

  mongodb:
    connection-string: mongodb://localhost:27017
    database: esselunga
    credentials:
      password: "Febbraio2024!"
      username: "slunga"
